spring:
   datasource:
      url: jdbc:mysql://47.100.197.51:3306/mall-wbs?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
      username: root
      password: ZHang521%99
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
         max-lifetime: 60000
         connection-test-query: SELECT 1
         pool-name: HikariPool-mall

   jpa:
      open-in-view: false
